#/*
# * Copyright (C) 2019-2020 Advanced Micro Devices, Inc. All rights reserved.
# */
obj-$(CONFIG_ARCH_MERO_CVIP) += biommu.o
obj-$(CONFIG_ARCH_MERO_CVIP) += cvip_dsp.o
ccflags-$(CONFIG_ARCH_MERO_CVIP) += -I$(srctree)/drivers/char
