# SPDX-License-Identifier: GPL-2.0+
# Mero platform Support
snd-pci-acp5x-i2s-objs	:= pci-acp5x-i2s.o
snd-acp5x-i2s-objs	:= acp5x-i2s.o
snd-acp5x-pcm-dma-objs	:= acp5x-pcm-dma.o
snd-soc-dummy-w5102-objs := dummy-w5102.o
snd-soc-acp5x-mach-objs := acp5x-dummy5102.o
obj-$(CONFIG_SND_SOC_AMD_ACP5x) += snd-pci-acp5x-i2s.o
obj-$(CONFIG_SND_SOC_AMD_ACP5x)	+= snd-acp5x-i2s.o
obj-$(CONFIG_SND_SOC_AMD_ACP5x) += snd-acp5x-pcm-dma.o
obj-$(CONFIG_SND_SOC_AMD_ACP5x)	+= snd-soc-dummy-w5102.o
obj-$(CONFIG_SND_SOC_AMD_ACP5x)	+= snd-soc-acp5x-mach.o
