#
# Makefile for Invensense inv-mpu-iio device.
#
obj-$(CONFIG_ML_INV_MPU) += inv_mpu_iio.o

inv_mpu_iio-objs += inv_mpu_common.o
inv_mpu_iio-objs += inv_mpu_ring.o
inv_mpu_iio-objs += inv_mpu_timestamp.o
inv_mpu_iio-objs += inv_mpu_dts.o

# chip support
inv_mpu_iio-objs += icm42600/inv_mpu_init_42600.o
inv_mpu_iio-objs += icm42600/inv_mpu_core_42600.o
inv_mpu_iio-objs += icm42600/inv_mpu_parsing_42600.o
inv_mpu_iio-objs += icm42600/inv_mpu_setup_42600.o
inv_mpu_iio-objs += icm42600/inv_mpu_misc_42600.o
inv_mpu_iio-objs += icm42600/inv_mpu_selftest_42600.o

# Bus support
#obj-$(CONFIG_ML_INV_MPU) += inv_mpu_i2c.o
obj-$(CONFIG_ML_INV_MPU) += inv_mpu_iio_spi.o
inv_mpu_iio_spi-objs += inv_mpu_spi.o

ccflags-y += -Wall -Werror
ccflags-y += -I$(src) -I$(src)/include
ccflags-y += -I$(srctree)/drivers/staging/android
ccflags-y += -DCONFIG_CRC32

# the modules have been condensed into one; kbuild will insert CONFIG_ML_INV_MPU automatically
# but we need to manually set these in order to get the compilation results we want
ccflags-y += -DCONFIG_INV_MPU_IIO_ICM42600=y -DCONFIG_INV_MPU_IIO_SPI=$(CONFIG_ML_INV_MPU)
