#
# Thermal zone driver for AMD Mero Subsystem
#
# Copyright (C) 2020 Advanced Micro Devices, Inc. All rights reserved.
#
obj-$(CONFIG_MERO_THERMAL)		+= mero_thermal_zone.o
obj-$(CONFIG_MERO_X86_THERMAL)		+= mero_x86_thermal.o
obj-$(CONFIG_MERO_SOC_THERMAL)		+= mero_soc_thermal.o
obj-$(CONFIG_MERO_GFX_THERMAL)		+= mero_gfx_thermal.o
obj-$(CONFIG_MERO_CVIP_THERMAL)		+= mero_cvip_thermal.o
