#
# SPDX-License-Identifier: GPL-2.0-only
#

obj-$(CONFIG_ML_MERO_SMMU) += mero_smmu.o

ccflags-y := -Wall -Werror
ccflags-y += -I$(srctree)/$(src)/../include
ccflags-y += -I$(srctree)/include/linux/cvip
