# SPDX-License-Identifier: GPL-2.0
#
# Makefile for Magic Leap misc devices
#

obj-$(CONFIG_MLMUX_FCMD)	+= mlmux_fcmd.o
obj-$(CONFIG_ML_VICON_RAVEN)	+= ml_vicon_raven.o
obj-$(CONFIG_ML_VICON_MERO)	+= ml_vicon_mero.o
obj-$(CONFIG_ML_AUDIO_LATENCY_MERO)	+= ml_audio_mero.o
