/*
 * amd_cam_metadata_tags.h
 *
 * Copyright (C) 2019-2022 Advanced Micro Devices, Inc. All rights reserved.
 *
 * This file is licensed under the terms of the GNU General Public License
 * version 2. This program is licensed "as is" without any warranty of any
 * kind, whether express or implied.
 *
 */

#ifndef __AMD_CAM_METADATA_TAGS_H__
#define __AMD_CAM_METADATA_TAGS_H__

#define AMD_CAM_VENDOR_SECTION 0x8000

enum amd_camera_metadata_section {
	AMD_CAM_COLOR_CORRECTION,
	AMD_CAM_CONTROL,
	AMD_CAM_DEMOSAIC,
	AMD_CAM_EDGE,
	AMD_CAM_FLASH,
	AMD_CAM_FLASH_INFO,
	AMD_CAM_HOT_PIXEL,
	AMD_CAM_JPEG,
	AMD_CAM_LENS,
	AMD_CAM_LENS_INFO,
	AMD_CAM_NOISE_REDUCTION,
	AMD_CAM_QUIRKS,
	AMD_CAM_REQUEST,
	AMD_CAM_SCALER,
	AMD_CAM_SENSOR,
	AMD_CAM_SENSOR_INFO,
	AMD_CAM_SHADING,
	AMD_CAM_STATISTICS,
	AMD_CAM_STATISTICS_INFO,
	AMD_CAM_TONEMAP,
	AMD_CAM_LED,
	AMD_CAM_INFO,
	AMD_CAM_BLACK_LEVEL,
	AMD_CAM_SYNC,
	AMD_CAM_REPROCESS,
	AMD_CAM_DEPTH,
	AMD_CAM_LOGICAL_MULTI_CAMERA,
	AMD_CAM_DISTORTION_CORRECTION,
	AMD_CAM_HEIC,
	AMD_CAM_HEIC_INFO,
	AMD_CAM_SECTION_COUNT,
};

enum amd_camera_metadata_vendor_section {
	AMD_CAM_VENDOR_CONTROL = AMD_CAM_VENDOR_SECTION,
	AMD_CAM_VENDOR_SECTION_END,
};

/**
 * Hierarchy positions in enum space. All vendor extension tags must be
 * defined with tag >= VENDOR_SECTION_START
 */
enum camera_metadata_section_start {
	AMD_CAM_COLOR_CORRECTION_START = AMD_CAM_COLOR_CORRECTION << 16,
	AMD_CAM_CONTROL_START = AMD_CAM_CONTROL << 16,
	AMD_CAM_DEMOSAIC_START = AMD_CAM_DEMOSAIC << 16,
	AMD_CAM_EDGE_START = AMD_CAM_EDGE << 16,
	AMD_CAM_FLASH_START = AMD_CAM_FLASH << 16,
	AMD_CAM_FLASH_INFO_START = AMD_CAM_FLASH_INFO << 16,
	AMD_CAM_HOT_PIXEL_START = AMD_CAM_HOT_PIXEL << 16,
	AMD_CAM_JPEG_START = AMD_CAM_JPEG << 16,
	AMD_CAM_LENS_START = AMD_CAM_LENS << 16,
	AMD_CAM_LENS_INFO_START = AMD_CAM_LENS_INFO << 16,
	AMD_CAM_NOISE_REDUCTION_START = AMD_CAM_NOISE_REDUCTION << 16,
	AMD_CAM_QUIRKS_START = AMD_CAM_QUIRKS << 16,
	AMD_CAM_REQUEST_START = AMD_CAM_REQUEST << 16,
	AMD_CAM_SCALER_START = AMD_CAM_SCALER << 16,
	AMD_CAM_SENSOR_START = AMD_CAM_SENSOR << 16,
	AMD_CAM_SENSOR_INFO_START = AMD_CAM_SENSOR_INFO << 16,
	AMD_CAM_SHADING_START = AMD_CAM_SHADING << 16,
	AMD_CAM_STATISTICS_START = AMD_CAM_STATISTICS << 16,
	AMD_CAM_STATISTICS_INFO_START = AMD_CAM_STATISTICS_INFO << 16,
	AMD_CAM_TONEMAP_START = AMD_CAM_TONEMAP << 16,
	AMD_CAM_LED_START = AMD_CAM_LED << 16,
	AMD_CAM_INFO_START = AMD_CAM_INFO << 16,
	AMD_CAM_BLACK_LEVEL_START = AMD_CAM_BLACK_LEVEL << 16,
	AMD_CAM_SYNC_START = AMD_CAM_SYNC << 16,
	AMD_CAM_REPROCESS_START = AMD_CAM_REPROCESS << 16,
	AMD_CAM_DEPTH_START = AMD_CAM_DEPTH << 16,
	AMD_CAM_LOGICAL_MULTI_CAMERA_START = AMD_CAM_LOGICAL_MULTI_CAMERA << 16,
	AMD_CAM_DISTORTION_CORRECTION_START
	    = AMD_CAM_DISTORTION_CORRECTION << 16,
	AMD_CAM_HEIC_START = AMD_CAM_HEIC << 16,
	AMD_CAM_HEIC_INFO_START = AMD_CAM_HEIC_INFO << 16,
	//Vendor section
	AMD_CAM_VENDOR_SECTION_START = AMD_CAM_VENDOR_CONTROL << 16,
	AMD_CAM_VENDOR_CONTROL_START = AMD_CAM_VENDOR_SECTION_START
};

/**
 * Main enum for defining camera metadata tags.  New entries must always go
 * before the section _END tag to preserve existing enumeration values.
 */
enum amd_camera_metadata_tag {
	AMD_CAM_COLOR_CORRECTION_MODE = AMD_CAM_COLOR_CORRECTION_START,
	AMD_CAM_COLOR_CORRECTION_TRANSFORM,
	AMD_CAM_COLOR_CORRECTION_GAINS,
	AMD_CAM_COLOR_CORRECTION_ABERRATION_MODE,
	AMD_CAM_COLOR_CORRECTION_AVAILABLE_ABERRATION_MODES,
	AMD_CAM_COLOR_CORRECTION_END,
	AMD_CAM_CONTROL_AE_ANTIBANDING_MODE = AMD_CAM_CONTROL_START,
	AMD_CAM_CONTROL_AE_EXPOSURE_COMPENSATION,
	AMD_CAM_CONTROL_AE_LOCK,
	AMD_CAM_CONTROL_AE_MODE,
	AMD_CAM_CONTROL_AE_REGIONS,
	AMD_CAM_CONTROL_AE_TARGET_FPS_RANGE,
	AMD_CAM_CONTROL_AE_PRECAPTURE_TRIGGER,
	AMD_CAM_CONTROL_AF_MODE,
	AMD_CAM_CONTROL_AF_REGIONS,
	AMD_CAM_CONTROL_AF_TRIGGER,
	AMD_CAM_CONTROL_AWB_LOCK,
	AMD_CAM_CONTROL_AWB_MODE,
	AMD_CAM_CONTROL_AWB_REGIONS,
	AMD_CAM_CONTROL_CAPTURE_INTENT,
	AMD_CAM_CONTROL_EFFECT_MODE,
	AMD_CAM_CONTROL_MODE,
	AMD_CAM_CONTROL_SCENE_MODE,
	AMD_CAM_CONTROL_VIDEO_STABILIZATION_MODE,
	AMD_CAM_CONTROL_AE_AVAILABLE_ANTIBANDING_MODES,
	AMD_CAM_CONTROL_AE_AVAILABLE_MODES,
	AMD_CAM_CONTROL_AE_AVAILABLE_TARGET_FPS_RANGES,
	AMD_CAM_CONTROL_AE_COMPENSATION_RANGE,
	AMD_CAM_CONTROL_AE_COMPENSATION_STEP,
	AMD_CAM_CONTROL_AF_AVAILABLE_MODES,
	AMD_CAM_CONTROL_AVAILABLE_EFFECTS,
	AMD_CAM_CONTROL_AVAILABLE_SCENE_MODES,
	AMD_CAM_CONTROL_AVAILABLE_VIDEO_STABILIZATION_MODES,
	AMD_CAM_CONTROL_AWB_AVAILABLE_MODES,
	AMD_CAM_CONTROL_MAX_REGIONS,
	AMD_CAM_CONTROL_SCENE_MODE_OVERRIDES,
	AMD_CAM_CONTROL_AE_PRECAPTURE_ID,
	AMD_CAM_CONTROL_AE_STATE,
	AMD_CAM_CONTROL_AF_STATE,
	AMD_CAM_CONTROL_AF_TRIGGER_ID,
	AMD_CAM_CONTROL_AWB_STATE,
	AMD_CAM_CONTROL_AVAILABLE_HIGH_SPEED_VIDEO_CONFIGURATIONS,
	AMD_CAM_CONTROL_AE_LOCK_AVAILABLE,
	AMD_CAM_CONTROL_AWB_LOCK_AVAILABLE,
	AMD_CAM_CONTROL_AVAILABLE_MODES,
	AMD_CAM_CONTROL_POST_RAW_SENSITIVITY_BOOST_RANGE,
	AMD_CAM_CONTROL_POST_RAW_SENSITIVITY_BOOST,
	AMD_CAM_CONTROL_ENABLE_ZSL,
	AMD_CAM_CONTROL_AF_SCENE_CHANGE,
	AMD_CAM_CONTROL_END,
	AMD_CAM_DEMOSAIC_MODE = AMD_CAM_DEMOSAIC_START,
	AMD_CAM_DEMOSAIC_END,
	AMD_CAM_EDGE_MODE = AMD_CAM_EDGE_START,
	AMD_CAM_EDGE_STRENGTH,
	AMD_CAM_EDGE_AVAILABLE_EDGE_MODES,
	AMD_CAM_EDGE_END,
	AMD_CAM_FLASH_FIRING_POWER = AMD_CAM_FLASH_START,
	AMD_CAM_FLASH_FIRING_TIME,
	AMD_CAM_FLASH_MODE,
	AMD_CAM_FLASH_COLOR_TEMPERATURE,
	AMD_CAM_FLASH_MAX_ENERGY,
	AMD_CAM_FLASH_STATE,
	AMD_CAM_FLASH_END,
	AMD_CAM_FLASH_INFO_AVAILABLE = AMD_CAM_FLASH_INFO_START,
	AMD_CAM_FLASH_INFO_CHARGE_DURATION,
	AMD_CAM_FLASH_INFO_END,
	AMD_CAM_HOT_PIXEL_MODE = AMD_CAM_HOT_PIXEL_START,
	AMD_CAM_HOT_PIXEL_AVAILABLE_HOT_PIXEL_MODES,
	AMD_CAM_HOT_PIXEL_END,
	AMD_CAM_JPEG_GPS_COORDINATES = AMD_CAM_JPEG_START,
	AMD_CAM_JPEG_GPS_PROCESSING_METHOD,
	AMD_CAM_JPEG_GPS_TIMESTAMP,
	AMD_CAM_JPEG_ORIENTATION,
	AMD_CAM_JPEG_QUALITY,
	AMD_CAM_JPEG_THUMBNAIL_QUALITY,
	AMD_CAM_JPEG_THUMBNAIL_SIZE,
	AMD_CAM_JPEG_AVAILABLE_THUMBNAIL_SIZES,
	AMD_CAM_JPEG_MAX_SIZE,
	AMD_CAM_JPEG_SIZE,
	AMD_CAM_JPEG_END,
	AMD_CAM_LENS_APERTURE = AMD_CAM_LENS_START,
	AMD_CAM_LENS_FILTER_DENSITY,
	AMD_CAM_LENS_FOCAL_LENGTH,
	AMD_CAM_LENS_FOCUS_DISTANCE,
	AMD_CAM_LENS_OPTICAL_STABILIZATION_MODE,
	AMD_CAM_LENS_FACING,
	AMD_CAM_LENS_POSE_ROTATION,
	AMD_CAM_LENS_POSE_TRANSLATION,
	AMD_CAM_LENS_FOCUS_RANGE,
	AMD_CAM_LENS_STATE,
	AMD_CAM_LENS_INTRINSIC_CALIBRATION,
	AMD_CAM_LENS_RADIAL_DISTORTION,
	AMD_CAM_LENS_POSE_REFERENCE,
	AMD_CAM_LENS_DISTORTION,
	AMD_CAM_LENS_END,
	AMD_CAM_LENS_INFO_AVAILABLE_APERTURES = AMD_CAM_LENS_INFO_START,
	AMD_CAM_LENS_INFO_AVAILABLE_FILTER_DENSITIES,
	AMD_CAM_LENS_INFO_AVAILABLE_FOCAL_LENGTHS,
	AMD_CAM_LENS_INFO_AVAILABLE_OPTICAL_STABILIZATION,
	AMD_CAM_LENS_INFO_HYPERFOCAL_DISTANCE,
	AMD_CAM_LENS_INFO_MINIMUM_FOCUS_DISTANCE,
	AMD_CAM_LENS_INFO_SHADING_MAP_SIZE,
	AMD_CAM_LENS_INFO_FOCUS_DISTANCE_CALIBRATION,
	AMD_CAM_LENS_INFO_END,
	AMD_CAM_NOISE_REDUCTION_MODE = AMD_CAM_NOISE_REDUCTION_START,
	AMD_CAM_NOISE_REDUCTION_STRENGTH,
	AMD_CAM_NOISE_REDUCTION_AVAILABLE_NOISE_REDUCTION_MODES,
	AMD_CAM_NOISE_REDUCTION_END,
	AMD_CAM_QUIRKS_METERING_CROP_REGION = AMD_CAM_QUIRKS_START,
	AMD_CAM_QUIRKS_TRIGGER_AF_WITH_AUTO,
	AMD_CAM_QUIRKS_USE_ZSL_FORMAT,
	AMD_CAM_QUIRKS_USE_PARTIAL_RESULT,
	AMD_CAM_QUIRKS_PARTIAL_RESULT,
	AMD_CAM_QUIRKS_END,
	AMD_CAM_REQUEST_FRAME_COUNT = AMD_CAM_REQUEST_START,
	AMD_CAM_REQUEST_ID,
	AMD_CAM_REQUEST_INPUT_STREAMS,
	AMD_CAM_REQUEST_METADATA_MODE,
	AMD_CAM_REQUEST_OUTPUT_STREAMS,
	AMD_CAM_REQUEST_TYPE,
	AMD_CAM_REQUEST_MAX_NUM_OUTPUT_STREAMS,
	AMD_CAM_REQUEST_MAX_NUM_REPROCESS_STREAMS,
	AMD_CAM_REQUEST_MAX_NUM_INPUT_STREAMS,
	AMD_CAM_REQUEST_PIPELINE_DEPTH,
	AMD_CAM_REQUEST_PIPELINE_MAX_DEPTH,
	AMD_CAM_REQUEST_PARTIAL_RESULT_COUNT,
	AMD_CAM_REQUEST_AVAILABLE_CAPABILITIES,
	AMD_CAM_REQUEST_AVAILABLE_REQUEST_KEYS,
	AMD_CAM_REQUEST_AVAILABLE_RESULT_KEYS,
	AMD_CAM_REQUEST_AVAILABLE_CHARACTERISTICS_KEYS,
	AMD_CAM_REQUEST_AVAILABLE_SESSION_KEYS,
	AMD_CAM_REQUEST_AVAILABLE_PHYSICAL_CAMERA_REQUEST_KEYS,
	AMD_CAM_REQUEST_CHARACTERISTIC_KEYS_NEEDING_PERMISSION,
	AMD_CAM_REQUEST_END,
	AMD_CAM_SCALER_CROP_REGION = AMD_CAM_SCALER_START,
	AMD_CAM_SCALER_AVAILABLE_FORMATS,
	AMD_CAM_SCALER_AVAILABLE_JPEG_MIN_DURATIONS,
	AMD_CAM_SCALER_AVAILABLE_JPEG_SIZES,
	AMD_CAM_SCALER_AVAILABLE_MAX_DIGITAL_ZOOM,
	AMD_CAM_SCALER_AVAILABLE_PROCESSED_MIN_DURATIONS,
	AMD_CAM_SCALER_AVAILABLE_PROCESSED_SIZES,
	AMD_CAM_SCALER_AVAILABLE_RAW_MIN_DURATIONS,
	AMD_CAM_SCALER_AVAILABLE_RAW_SIZES,
	AMD_CAM_SCALER_AVAILABLE_INPUT_OUTPUT_FORMATS_MAP,
	AMD_CAM_SCALER_AVAILABLE_STREAM_CONFIGURATIONS,
	AMD_CAM_SCALER_AVAILABLE_MIN_FRAME_DURATIONS,
	AMD_CAM_SCALER_AVAILABLE_STALL_DURATIONS,
	AMD_CAM_SCALER_CROPPING_TYPE,
	AMD_CAM_SCALER_AVAILABLE_RECOMMENDED_STREAM_CONFIGURATIONS,
	AMD_CAM_SCALER_AVAILABLE_RECOMMENDED_INPUT_OUTPUT_FORMATS_MAP,
	AMD_CAM_SCALER_END,
	AMD_CAM_SENSOR_EXPOSURE_TIME = AMD_CAM_SENSOR_START,
	AMD_CAM_SENSOR_FRAME_DURATION,
	AMD_CAM_SENSOR_SENSITIVITY,
	AMD_CAM_SENSOR_REFERENCE_ILLUMINANT1,
	AMD_CAM_SENSOR_REFERENCE_ILLUMINANT2,
	AMD_CAM_SENSOR_CALIBRATION_TRANSFORM1,
	AMD_CAM_SENSOR_CALIBRATION_TRANSFORM2,
	AMD_CAM_SENSOR_COLOR_TRANSFORM1,
	AMD_CAM_SENSOR_COLOR_TRANSFORM2,
	AMD_CAM_SENSOR_FORWARD_MATRIX1,
	AMD_CAM_SENSOR_FORWARD_MATRIX2,
	AMD_CAM_SENSOR_BASE_GAIN_FACTOR,
	AMD_CAM_SENSOR_BLACK_LEVEL_PATTERN,
	AMD_CAM_SENSOR_MAX_ANALOG_SENSITIVITY,
	AMD_CAM_SENSOR_ORIENTATION,
	AMD_CAM_SENSOR_PROFILE_HUE_SAT_MAP_DIMENSIONS,
	AMD_CAM_SENSOR_TIMESTAMP,
	AMD_CAM_SENSOR_TEMPERATURE,
	AMD_CAM_SENSOR_NEUTRAL_COLOR_POINT,
	AMD_CAM_SENSOR_NOISE_PROFILE,
	AMD_CAM_SENSOR_PROFILE_HUE_SAT_MAP,
	AMD_CAM_SENSOR_PROFILE_TONE_CURVE,
	AMD_CAM_SENSOR_GREEN_SPLIT,
	AMD_CAM_SENSOR_TEST_PATTERN_DATA,
	AMD_CAM_SENSOR_TEST_PATTERN_MODE,
	AMD_CAM_SENSOR_AVAILABLE_TEST_PATTERN_MODES,
	AMD_CAM_SENSOR_ROLLING_SHUTTER_SKEW,
	AMD_CAM_SENSOR_OPTICAL_BLACK_REGIONS,
	AMD_CAM_SENSOR_DYNAMIC_BLACK_LEVEL,
	AMD_CAM_SENSOR_DYNAMIC_WHITE_LEVEL,
	AMD_CAM_SENSOR_OPAQUE_RAW_SIZE,
	AMD_CAM_SENSOR_END,
	AMD_CAM_SENSOR_INFO_ACTIVE_ARRAY_SIZE = AMD_CAM_SENSOR_INFO_START,
	AMD_CAM_SENSOR_INFO_SENSITIVITY_RANGE,
	AMD_CAM_SENSOR_INFO_COLOR_FILTER_ARRANGEMENT,
	AMD_CAM_SENSOR_INFO_EXPOSURE_TIME_RANGE,
	AMD_CAM_SENSOR_INFO_MAX_FRAME_DURATION,
	AMD_CAM_SENSOR_INFO_PHYSICAL_SIZE,
	AMD_CAM_SENSOR_INFO_PIXEL_ARRAY_SIZE,
	AMD_CAM_SENSOR_INFO_WHITE_LEVEL,
	AMD_CAM_SENSOR_INFO_TIMESTAMP_SOURCE,
	AMD_CAM_SENSOR_INFO_LENS_SHADING_APPLIED,
	AMD_CAM_SENSOR_INFO_PRE_CORRECTION_ACTIVE_ARRAY_SIZE,
	AMD_CAM_SENSOR_INFO_END,
	AMD_CAM_SHADING_MODE = AMD_CAM_SHADING_START,
	AMD_CAM_SHADING_STRENGTH,
	AMD_CAM_SHADING_AVAILABLE_MODES,
	AMD_CAM_SHADING_END,
	AMD_CAM_STATISTICS_FACE_DETECT_MODE = AMD_CAM_STATISTICS_START,
	AMD_CAM_STATISTICS_HISTOGRAM_MODE,
	AMD_CAM_STATISTICS_SHARPNESS_MAP_MODE,
	AMD_CAM_STATISTICS_HOT_PIXEL_MAP_MODE,
	AMD_CAM_STATISTICS_FACE_IDS,
	AMD_CAM_STATISTICS_FACE_LANDMARKS,
	AMD_CAM_STATISTICS_FACE_RECTANGLES,
	AMD_CAM_STATISTICS_FACE_SCORES,
	AMD_CAM_STATISTICS_HISTOGRAM,
	AMD_CAM_STATISTICS_SHARPNESS_MAP,
	AMD_CAM_STATISTICS_LENS_SHADING_CORRECTION_MAP,
	AMD_CAM_STATISTICS_LENS_SHADING_MAP,
	AMD_CAM_STATISTICS_PREDICTED_COLOR_GAINS,
	AMD_CAM_STATISTICS_PREDICTED_COLOR_TRANSFORM,
	AMD_CAM_STATISTICS_SCENE_FLICKER,
	AMD_CAM_STATISTICS_HOT_PIXEL_MAP,
	AMD_CAM_STATISTICS_LENS_SHADING_MAP_MODE,
	AMD_CAM_STATISTICS_OIS_DATA_MODE,
	AMD_CAM_STATISTICS_OIS_TIMESTAMPS,
	AMD_CAM_STATISTICS_OIS_X_SHIFTS,
	AMD_CAM_STATISTICS_OIS_Y_SHIFTS,
	AMD_CAM_STATISTICS_END,
	AMD_CAM_STATISTICS_INFO_AVAILABLE_FACE_DETECT_MODES =
	    AMD_CAM_STATISTICS_INFO_START,
	AMD_CAM_STATISTICS_INFO_HISTOGRAM_BUCKET_COUNT,
	AMD_CAM_STATISTICS_INFO_MAX_FACE_COUNT,
	AMD_CAM_STATISTICS_INFO_MAX_HISTOGRAM_COUNT,
	AMD_CAM_STATISTICS_INFO_MAX_SHARPNESS_MAP_VALUE,
	AMD_CAM_STATISTICS_INFO_SHARPNESS_MAP_SIZE,
	AMD_CAM_STATISTICS_INFO_AVAILABLE_HOT_PIXEL_MAP_MODES,
	AMD_CAM_STATISTICS_INFO_AVAILABLE_LENS_SHADING_MAP_MODES,
	AMD_CAM_STATISTICS_INFO_AVAILABLE_OIS_DATA_MODES,
	AMD_CAM_STATISTICS_INFO_END,
	AMD_CAM_TONEMAP_CURVE_BLUE = AMD_CAM_TONEMAP_START,
	AMD_CAM_TONEMAP_CURVE_GREEN,
	AMD_CAM_TONEMAP_CURVE_RED,
	AMD_CAM_TONEMAP_MODE,
	AMD_CAM_TONEMAP_MAX_CURVE_POINTS,
	AMD_CAM_TONEMAP_AVAILABLE_TONE_MAP_MODES,
	AMD_CAM_TONEMAP_GAMMA,
	AMD_CAM_TONEMAP_PRESET_CURVE,
	AMD_CAM_TONEMAP_END,
	AMD_CAM_LED_TRANSMIT = AMD_CAM_LED_START,
	AMD_CAM_LED_AVAILABLE_LEDS,
	AMD_CAM_LED_END,
	AMD_CAM_INFO_SUPPORTED_HARDWARE_LEVEL = AMD_CAM_INFO_START,
	AMD_CAM_INFO_VERSION,
	AMD_CAM_INFO_SUPPORTED_BUFFER_MANAGEMENT_VERSION,
	AMD_CAM_INFO_END,
	AMD_CAM_BLACK_LEVEL_LOCK = AMD_CAM_BLACK_LEVEL_START,
	AMD_CAM_BLACK_LEVEL_END,
	AMD_CAM_SYNC_FRAME_NUMBER = AMD_CAM_SYNC_START,
	AMD_CAM_SYNC_MAX_LATENCY,
	AMD_CAM_SYNC_END,
	AMD_CAM_REPROCESS_EFFECTIVE_EXPOSURE_FACTOR = AMD_CAM_REPROCESS_START,
	AMD_CAM_REPROCESS_MAX_CAPTURE_STALL,
	AMD_CAM_REPROCESS_END,
	AMD_CAM_DEPTH_MAX_DEPTH_SAMPLES = AMD_CAM_DEPTH_START,
	AMD_CAM_DEPTH_AVAILABLE_DEPTH_STREAM_CONFIGURATIONS,
	AMD_CAM_DEPTH_AVAILABLE_DEPTH_MIN_FRAME_DURATIONS,
	AMD_CAM_DEPTH_AVAILABLE_DEPTH_STALL_DURATIONS,
	AMD_CAM_DEPTH_DEPTH_IS_EXCLUSIVE,
	AMD_CAM_DEPTH_AVAILABLE_RECOMMENDED_DEPTH_STREAM_CONFIGURATIONS,
	AMD_CAM_DEPTH_AVAILABLE_DYNAMIC_DEPTH_STREAM_CONFIGURATIONS,
	AMD_CAM_DEPTH_AVAILABLE_DYNAMIC_DEPTH_MIN_FRAME_DURATIONS,
	AMD_CAM_DEPTH_AVAILABLE_DYNAMIC_DEPTH_STALL_DURATIONS,
	AMD_CAM_DEPTH_END,
	AMD_CAM_LOGICAL_MULTI_CAMERA_PHYSICAL_IDS =
	    AMD_CAM_LOGICAL_MULTI_CAMERA_START,
	AMD_CAM_LOGICAL_MULTI_CAMERA_SENSOR_SYNC_TYPE,
	AMD_CAM_LOGICAL_MULTI_CAMERA_ACTIVE_PHYSICAL_ID,
	AMD_CAM_LOGICAL_MULTI_CAMERA_END,
	AMD_CAM_DISTORTION_CORRECTION_MODE =
	    AMD_CAM_DISTORTION_CORRECTION_START,
	AMD_CAM_DISTORTION_CORRECTION_AVAILABLE_MODES,
	AMD_CAM_DISTORTION_CORRECTION_END,
	AMD_CAM_HEIC_AVAILABLE_HEIC_STREAM_CONFIGURATIONS = AMD_CAM_HEIC_START,
	AMD_CAM_HEIC_AVAILABLE_HEIC_MIN_FRAME_DURATIONS,
	AMD_CAM_HEIC_AVAILABLE_HEIC_STALL_DURATIONS,
	AMD_CAM_HEIC_END,
	AMD_CAM_HEIC_INFO_SUPPORTED = AMD_CAM_HEIC_INFO_START,
	AMD_CAM_HEIC_INFO_MAX_JPEG_APP_SEGMENTS_COUNT,
	AMD_CAM_HEIC_INFO_END,
// AMD Vendor tags
	AMD_CAM_VENDOR_CONTROL_FORCEAPPLY_MODE = AMD_CAM_VENDOR_CONTROL_START,
	AMD_CAM_VENDOR_CONTROL_AVAILABLE_FORCEAPPLY_MODES,
	AMD_CAM_VENDOR_CONTROL_EFFECT_MODE,
	AMD_CAM_VENDOR_CONTROL_AVAILABLE_EFFECT_MODES,
	AMD_CAM_VENDOR_CONTROL_APP_EXPOSURE_TIME_UPPER_LIMIT,
	AMD_CAM_VENDOR_CONTROL_LENS_CONTROL_MODE,
	AMD_CAM_VENDOR_CONTROL_AVAILABLE_LENS_CONTROL_MODES,
	AMD_CAM_VENDOR_CONTROL_ENGINEERING_MODE,
	AMD_CAM_VENDOR_CONTROL_AVAILABLE_ENGINEERING_MODES,
	AMD_CAM_VENDOR_CONTROL_LENS_SWEEP_DISTANCERANGE,
	AMD_CAM_VENDOR_CONTROL_LENS_INFO_MIN_INCREMENT,
	AMD_CAM_VENDOR_CONTROL_CVIP_TIMESTAMPS,
	AMD_CAM_VENDOR_CONTROL_AE_TOUCH_TARGET_RANGE,
	AMD_CAM_VENDOR_CONTROL_AE_TOUCH_TARGET,
	AMD_CAM_VENDOR_CONTROL_AE_TOUCH_TARGET_WEIGHT_RANGE,
	AMD_CAM_VENDOR_CONTROL_AE_TOUCH_TARGET_WEIGHT,
	AMD_CAM_VENDOR_CONTROL_RAW_FRAME_ID,
	AMD_CAM_VENDOR_CONTROL_CVIP_AF_FRAME_ID,
	AMD_CAM_VENDOR_CONTROL_END,
};

/**
 * Enumeration definitions for the various entries that need them
 */
// AMD_CAM_COLOR_CORRECTION_MODE
enum camera_metadata_enum_amd_cam_color_correction_mode {
	AMD_CAM_COLOR_CORRECTION_MODE_TRANSFORM_MATRIX,
	AMD_CAM_COLOR_CORRECTION_MODE_FAST,
	AMD_CAM_COLOR_CORRECTION_MODE_HIGH_QUALITY,
};

// AMD_CAM_COLOR_CORRECTION_ABERRATION_MODE
enum camera_metadata_enum_amd_cam_color_correction_aberration_mode {
	AMD_CAM_COLOR_CORRECTION_ABERRATION_MODE_OFF,
	AMD_CAM_COLOR_CORRECTION_ABERRATION_MODE_FAST,
	AMD_CAM_COLOR_CORRECTION_ABERRATION_MODE_HIGH_QUALITY,
};

// AMD_CAM_CONTROL_AE_ANTIBANDING_MODE
enum camera_metadata_enum_amd_cam_control_ae_antibanding_mode {
	AMD_CAM_CONTROL_AE_ANTIBANDING_MODE_OFF,
	AMD_CAM_CONTROL_AE_ANTIBANDING_MODE_50HZ,
	AMD_CAM_CONTROL_AE_ANTIBANDING_MODE_60HZ,
	AMD_CAM_CONTROL_AE_ANTIBANDING_MODE_AUTO,
};

// AMD_CAM_CONTROL_AE_LOCK
enum camera_metadata_enum_amd_cam_control_ae_lock {
	AMD_CAM_CONTROL_AE_LOCK_OFF,
	AMD_CAM_CONTROL_AE_LOCK_ON,
};

// AMD_CAM_CONTROL_AE_MODE
enum camera_metadata_enum_amd_cam_control_ae_mode {
	AMD_CAM_CONTROL_AE_MODE_OFF,
	AMD_CAM_CONTROL_AE_MODE_ON,
	AMD_CAM_CONTROL_AE_MODE_ON_AUTO_FLASH,
	AMD_CAM_CONTROL_AE_MODE_ON_ALWAYS_FLASH,
	AMD_CAM_CONTROL_AE_MODE_ON_AUTO_FLASH_REDEYE,
	AMD_CAM_CONTROL_AE_MODE_ON_EXTERNAL_FLASH,
};

// AMD_CAM_CONTROL_AE_PRECAPTURE_TRIGGER
enum camera_metadata_enum_amd_cam_control_ae_precapture_trigger {
	AMD_CAM_CONTROL_AE_PRECAPTURE_TRIGGER_IDLE,
	AMD_CAM_CONTROL_AE_PRECAPTURE_TRIGGER_START,
	AMD_CAM_CONTROL_AE_PRECAPTURE_TRIGGER_CANCEL,
};

// AMD_CAM_CONTROL_AF_MODE
enum camera_metadata_enum_amd_cam_control_af_mode {
	AMD_CAM_CONTROL_AF_MODE_OFF,
	AMD_CAM_CONTROL_AF_MODE_AUTO,
	AMD_CAM_CONTROL_AF_MODE_MACRO,
	AMD_CAM_CONTROL_AF_MODE_CONTINUOUS_VIDEO,
	AMD_CAM_CONTROL_AF_MODE_CONTINUOUS_PICTURE,
	AMD_CAM_CONTROL_AF_MODE_EDOF,
};

// AMD_CAM_CONTROL_AF_TRIGGER
enum camera_metadata_enum_amd_cam_control_af_trigger {
	AMD_CAM_CONTROL_AF_TRIGGER_IDLE,
	AMD_CAM_CONTROL_AF_TRIGGER_START,
	AMD_CAM_CONTROL_AF_TRIGGER_CANCEL,
};

// AMD_CAM_CONTROL_AWB_LOCK
enum camera_metadata_enum_amd_cam_control_awb_lock {
	AMD_CAM_CONTROL_AWB_LOCK_OFF,
	AMD_CAM_CONTROL_AWB_LOCK_ON,
};

// AMD_CAM_CONTROL_AWB_MODE
enum camera_metadata_enum_amd_cam_control_awb_mode {
	AMD_CAM_CONTROL_AWB_MODE_OFF,
	AMD_CAM_CONTROL_AWB_MODE_AUTO,
	AMD_CAM_CONTROL_AWB_MODE_INCANDESCENT,
	AMD_CAM_CONTROL_AWB_MODE_FLUORESCENT,
	AMD_CAM_CONTROL_AWB_MODE_WARM_FLUORESCENT,
	AMD_CAM_CONTROL_AWB_MODE_DAYLIGHT,
	AMD_CAM_CONTROL_AWB_MODE_CLOUDY_DAYLIGHT,
	AMD_CAM_CONTROL_AWB_MODE_TWILIGHT,
	AMD_CAM_CONTROL_AWB_MODE_SHADE,
};

// AMD_CAM_CONTROL_CAPTURE_INTENT
enum camera_metadata_enum_amd_cam_control_capture_intent {
	AMD_CAM_CONTROL_CAPTURE_INTENT_CUSTOM,
	AMD_CAM_CONTROL_CAPTURE_INTENT_PREVIEW,
	AMD_CAM_CONTROL_CAPTURE_INTENT_STILL_CAPTURE,
	AMD_CAM_CONTROL_CAPTURE_INTENT_VIDEO_RECORD,
	AMD_CAM_CONTROL_CAPTURE_INTENT_VIDEO_SNAPSHOT,
	AMD_CAM_CONTROL_CAPTURE_INTENT_ZERO_SHUTTER_LAG,
	AMD_CAM_CONTROL_CAPTURE_INTENT_MANUAL,
	AMD_CAM_CONTROL_CAPTURE_INTENT_MOTION_TRACKING,
};

// AMD_CAM_CONTROL_EFFECT_MODE
enum camera_metadata_enum_amd_cam_control_effect_mode {
	AMD_CAM_CONTROL_EFFECT_MODE_OFF,
	AMD_CAM_CONTROL_EFFECT_MODE_MONO,
	AMD_CAM_CONTROL_EFFECT_MODE_NEGATIVE,
	AMD_CAM_CONTROL_EFFECT_MODE_SOLARIZE,
	AMD_CAM_CONTROL_EFFECT_MODE_SEPIA,
	AMD_CAM_CONTROL_EFFECT_MODE_POSTERIZE,
	AMD_CAM_CONTROL_EFFECT_MODE_WHITEBOARD,
	AMD_CAM_CONTROL_EFFECT_MODE_BLACKBOARD,
	AMD_CAM_CONTROL_EFFECT_MODE_AQUA,
};

// AMD_CAM_CONTROL_MODE
enum camera_metadata_enum_amd_cam_control_mode {
	AMD_CAM_CONTROL_MODE_OFF,
	AMD_CAM_CONTROL_MODE_AUTO,
	AMD_CAM_CONTROL_MODE_USE_SCENE_MODE,
	AMD_CAM_CONTROL_MODE_OFF_KEEP_STATE,
};

// AMD_CAM_CONTROL_SCENE_MODE
enum camera_metadata_enum_amd_cam_control_scene_mode {
	AMD_CAM_CONTROL_SCENE_MODE_DISABLED = 0,
	AMD_CAM_CONTROL_SCENE_MODE_FACE_PRIORITY,
	AMD_CAM_CONTROL_SCENE_MODE_ACTION,
	AMD_CAM_CONTROL_SCENE_MODE_PORTRAIT,
	AMD_CAM_CONTROL_SCENE_MODE_LANDSCAPE,
	AMD_CAM_CONTROL_SCENE_MODE_NIGHT,
	AMD_CAM_CONTROL_SCENE_MODE_NIGHT_PORTRAIT,
	AMD_CAM_CONTROL_SCENE_MODE_THEATRE,
	AMD_CAM_CONTROL_SCENE_MODE_BEACH,
	AMD_CAM_CONTROL_SCENE_MODE_SNOW,
	AMD_CAM_CONTROL_SCENE_MODE_SUNSET,
	AMD_CAM_CONTROL_SCENE_MODE_STEADYPHOTO,
	AMD_CAM_CONTROL_SCENE_MODE_FIREWORKS,
	AMD_CAM_CONTROL_SCENE_MODE_SPORTS,
	AMD_CAM_CONTROL_SCENE_MODE_PARTY,
	AMD_CAM_CONTROL_SCENE_MODE_CANDLELIGHT,
	AMD_CAM_CONTROL_SCENE_MODE_BARCODE,
	AMD_CAM_CONTROL_SCENE_MODE_HIGH_SPEED_VIDEO,
	AMD_CAM_CONTROL_SCENE_MODE_HDR,
	AMD_CAM_CONTROL_SCENE_MODE_FACE_PRIORITY_LOW_LIGHT,
	AMD_CAM_CONTROL_SCENE_MODE_DEVICE_CUSTOM_START = 100,
	AMD_CAM_CONTROL_SCENE_MODE_CUSTOM_MEDICAL =
		AMD_CAM_CONTROL_SCENE_MODE_DEVICE_CUSTOM_START,
	AMD_CAM_CONTROL_SCENE_MODE_DEVICE_CUSTOM_END = 127,
};

// AMD_CAM_CONTROL_VIDEO_STABILIZATION_MODE
enum camera_metadata_enum_amd_cam_control_video_stabilization_mode {
	AMD_CAM_CONTROL_VIDEO_STABILIZATION_MODE_OFF,
	AMD_CAM_CONTROL_VIDEO_STABILIZATION_MODE_ON,
};

// AMD_CAM_CONTROL_AE_STATE
enum camera_metadata_enum_amd_cam_control_ae_state {
	AMD_CAM_CONTROL_AE_STATE_INACTIVE,
	AMD_CAM_CONTROL_AE_STATE_SEARCHING,
	AMD_CAM_CONTROL_AE_STATE_CONVERGED,
	AMD_CAM_CONTROL_AE_STATE_LOCKED,
	AMD_CAM_CONTROL_AE_STATE_FLASH_REQUIRED,
	AMD_CAM_CONTROL_AE_STATE_PRECAPTURE,
};

// AMD_CAM_CONTROL_AF_STATE
enum camera_metadata_enum_amd_cam_control_af_state {
	AMD_CAM_CONTROL_AF_STATE_INACTIVE,
	AMD_CAM_CONTROL_AF_STATE_PASSIVE_SCAN,
	AMD_CAM_CONTROL_AF_STATE_PASSIVE_FOCUSED,
	AMD_CAM_CONTROL_AF_STATE_ACTIVE_SCAN,
	AMD_CAM_CONTROL_AF_STATE_FOCUSED_LOCKED,
	AMD_CAM_CONTROL_AF_STATE_NOT_FOCUSED_LOCKED,
	AMD_CAM_CONTROL_AF_STATE_PASSIVE_UNFOCUSED,
};

// AMD_CAM_CONTROL_AWB_STATE
enum camera_metadata_enum_amd_cam_control_awb_state {
	AMD_CAM_CONTROL_AWB_STATE_INACTIVE,
	AMD_CAM_CONTROL_AWB_STATE_SEARCHING,
	AMD_CAM_CONTROL_AWB_STATE_CONVERGED,
	AMD_CAM_CONTROL_AWB_STATE_LOCKED,
};

// AMD_CAM_CONTROL_AE_LOCK_AVAILABLE
enum camera_metadata_enum_amd_cam_control_ae_lock_available {
	AMD_CAM_CONTROL_AE_LOCK_AVAILABLE_FALSE,
	AMD_CAM_CONTROL_AE_LOCK_AVAILABLE_TRUE,
};

// AMD_CAM_CONTROL_AWB_LOCK_AVAILABLE
enum camera_metadata_enum_amd_cam_control_awb_lock_available {
	AMD_CAM_CONTROL_AWB_LOCK_AVAILABLE_FALSE,
	AMD_CAM_CONTROL_AWB_LOCK_AVAILABLE_TRUE,
};

// AMD_CAM_CONTROL_ENABLE_ZSL
enum camera_metadata_enum_amd_cam_control_enable_zsl {
	AMD_CAM_CONTROL_ENABLE_ZSL_FALSE,
	AMD_CAM_CONTROL_ENABLE_ZSL_TRUE,
};

// AMD_CAM_CONTROL_AF_SCENE_CHANGE
enum camera_metadata_enum_amd_cam_control_af_scene_change {
	AMD_CAM_CONTROL_AF_SCENE_CHANGE_NOT_DETECTED,
	AMD_CAM_CONTROL_AF_SCENE_CHANGE_DETECTED,
};

// AMD_CAM_DEMOSAIC_MODE
enum camera_metadata_enum_amd_cam_demosaic_mode {
	AMD_CAM_DEMOSAIC_MODE_FAST,
	AMD_CAM_DEMOSAIC_MODE_HIGH_QUALITY,
};

// AMD_CAM_EDGE_MODE
enum camera_metadata_enum_amd_cam_edge_mode {
	AMD_CAM_EDGE_MODE_OFF,
	AMD_CAM_EDGE_MODE_FAST,
	AMD_CAM_EDGE_MODE_HIGH_QUALITY,
	AMD_CAM_EDGE_MODE_ZERO_SHUTTER_LAG,
};

// AMD_CAM_FLASH_MODE
enum camera_metadata_enum_amd_cam_flash_mode {
	AMD_CAM_FLASH_MODE_OFF,
	AMD_CAM_FLASH_MODE_SINGLE,
	AMD_CAM_FLASH_MODE_TORCH,
};

// AMD_CAM_FLASH_STATE
enum camera_metadata_enum_amd_cam_flash_state {
	AMD_CAM_FLASH_STATE_UNAVAILABLE,
	AMD_CAM_FLASH_STATE_CHARGING,
	AMD_CAM_FLASH_STATE_READY,
	AMD_CAM_FLASH_STATE_FIRED,
	AMD_CAM_FLASH_STATE_PARTIAL,
};

// AMD_CAM_FLASH_INFO_AVAILABLE
enum camera_metadata_enum_amd_cam_flash_info_available {
	AMD_CAM_FLASH_INFO_AVAILABLE_FALSE,
	AMD_CAM_FLASH_INFO_AVAILABLE_TRUE,
};

// AMD_CAM_HOT_PIXEL_MODE
enum camera_metadata_enum_amd_cam_hot_pixel_mode {
	AMD_CAM_HOT_PIXEL_MODE_OFF,
	AMD_CAM_HOT_PIXEL_MODE_FAST,
	AMD_CAM_HOT_PIXEL_MODE_HIGH_QUALITY,
};

// AMD_CAM_LENS_OPTICAL_STABILIZATION_MODE
enum camera_metadata_enum_amd_cam_lens_optical_stabilization_mode {
	AMD_CAM_LENS_OPTICAL_STABILIZATION_MODE_OFF,
	AMD_CAM_LENS_OPTICAL_STABILIZATION_MODE_ON,
};

// AMD_CAM_LENS_FACING
enum camera_metadata_enum_amd_cam_lens_facing {
	AMD_CAM_LENS_FACING_FRONT,
	AMD_CAM_LENS_FACING_BACK,
	AMD_CAM_LENS_FACING_EXTERNAL,
};

// AMD_CAM_LENS_STATE
enum camera_metadata_enum_amd_cam_lens_state {
	AMD_CAM_LENS_STATE_STATIONARY,
	AMD_CAM_LENS_STATE_MOVING,
};

// AMD_CAM_LENS_POSE_REFERENCE
enum camera_metadata_enum_amd_cam_lens_pose_reference {
	AMD_CAM_LENS_POSE_REFERENCE_PRIMARY_CAMERA,
	AMD_CAM_LENS_POSE_REFERENCE_GYROSCOPE,
};

// AMD_CAM_LENS_INFO_FOCUS_DISTANCE_CALIBRATION
enum camera_metadata_enum_amd_cam_lens_info_focus_distance_calibration {
	AMD_CAM_LENS_INFO_FOCUS_DISTANCE_CALIBRATION_UNCALIBRATED,
	AMD_CAM_LENS_INFO_FOCUS_DISTANCE_CALIBRATION_APPROXIMATE,
	AMD_CAM_LENS_INFO_FOCUS_DISTANCE_CALIBRATION_CALIBRATED,
};

// AMD_CAM_NOISE_REDUCTION_MODE
enum camera_metadata_enum_amd_cam_noise_reduction_mode {
	AMD_CAM_NOISE_REDUCTION_MODE_OFF,
	AMD_CAM_NOISE_REDUCTION_MODE_FAST,
	AMD_CAM_NOISE_REDUCTION_MODE_HIGH_QUALITY,
	AMD_CAM_NOISE_REDUCTION_MODE_MINIMAL,
	AMD_CAM_NOISE_REDUCTION_MODE_ZERO_SHUTTER_LAG,
};

// AMD_CAM_QUIRKS_PARTIAL_RESULT
enum camera_metadata_enum_amd_cam_quirks_partial_result {
	AMD_CAM_QUIRKS_PARTIAL_RESULT_FINAL,
	AMD_CAM_QUIRKS_PARTIAL_RESULT_PARTIAL,
};

// AMD_CAM_REQUEST_METADATA_MODE
enum camera_metadata_enum_amd_cam_request_metadata_mode {
	AMD_CAM_REQUEST_METADATA_MODE_NONE,
	AMD_CAM_REQUEST_METADATA_MODE_FULL,
};

// AMD_CAM_REQUEST_TYPE
enum camera_metadata_enum_amd_cam_request_type {
	AMD_CAM_REQUEST_TYPE_CAPTURE,
	AMD_CAM_REQUEST_TYPE_REPROCESS,
};

// AMD_CAM_REQUEST_AVAILABLE_CAPABILITIES
enum camera_metadata_enum_amd_cam_request_available_capabilities {
	AMD_CAM_REQUEST_AVAILABLE_CAPABILITIES_BACKWARD_COMPATIBLE,
	AMD_CAM_REQUEST_AVAILABLE_CAPABILITIES_MANUAL_SENSOR,
	AMD_CAM_REQUEST_AVAILABLE_CAPABILITIES_MANUAL_POST_PROCESSING,
	AMD_CAM_REQUEST_AVAILABLE_CAPABILITIES_RAW,
	AMD_CAM_REQUEST_AVAILABLE_CAPABILITIES_PRIVATE_REPROCESSING,
	AMD_CAM_REQUEST_AVAILABLE_CAPABILITIES_READ_SENSOR_SETTINGS,
	AMD_CAM_REQUEST_AVAILABLE_CAPABILITIES_BURST_CAPTURE,
	AMD_CAM_REQUEST_AVAILABLE_CAPABILITIES_YUV_REPROCESSING,
	AMD_CAM_REQUEST_AVAILABLE_CAPABILITIES_DEPTH_OUTPUT,
	AMD_CAM_REQUEST_AVAILABLE_CAPABILITIES_CONSTRAINED_HIGH_SPEED_VIDEO,
	AMD_CAM_REQUEST_AVAILABLE_CAPABILITIES_MOTION_TRACKING,
	AMD_CAM_REQUEST_AVAILABLE_CAPABILITIES_LOGICAL_MULTI_CAMERA,
	AMD_CAM_REQUEST_AVAILABLE_CAPABILITIES_MONOCHROME,
	AMD_CAM_REQUEST_AVAILABLE_CAPABILITIES_SECURE_IMAGE_DATA,
};

// AMD_CAM_SCALER_AVAILABLE_FORMATS
enum camera_metadata_enum_amd_cam_scaler_available_formats {
	AMD_CAM_SCALER_AVAILABLE_FORMATS_RAW16 = 0x20,
	AMD_CAM_SCALER_AVAILABLE_FORMATS_RAW_OPAQUE = 0x24,
	AMD_CAM_SCALER_AVAILABLE_FORMATS_YV12 = 0x32315659,
	AMD_CAM_SCALER_AVAILABLE_FORMATS_YCrCb_420_SP = 0x11,
	AMD_CAM_SCALER_AVAILABLE_FORMATS_IMPLEMENTATION_DEFINED = 0x22,
	AMD_CAM_SCALER_AVAILABLE_FORMATS_YCbCr_420_888 = 0x23,
	AMD_CAM_SCALER_AVAILABLE_FORMATS_BLOB = 0x21,
	AMD_CAM_SCALER_AVAILABLE_FORMATS_RAW10 = 0x25,
	AMD_CAM_SCALER_AVAILABLE_FORMATS_RAW12 = 0x26,
	AMD_CAM_SCALER_AVAILABLE_FORMATS_Y8 = 0x20203859,
};

// AMD_CAM_SCALER_AVAILABLE_STREAM_CONFIGURATIONS
enum camera_metadata_enum_amd_cam_scaler_available_stream_configurations {
	AMD_CAM_SCALER_AVAILABLE_STREAM_CONFIGURATIONS_OUTPUT,
	AMD_CAM_SCALER_AVAILABLE_STREAM_CONFIGURATIONS_INPUT,
};

// AMD_CAM_SCALER_CROPPING_TYPE
enum camera_metadata_enum_amd_cam_scaler_cropping_type {
	AMD_CAM_SCALER_CROPPING_TYPE_CENTER_ONLY,
	AMD_CAM_SCALER_CROPPING_TYPE_FREEFORM,
};

// AMD_CAM_SCALER_AVAILABLE_RECOMMENDED_STREAM_CONFIGURATIONS
enum enum_amd_cam_scaler_available_recommended_stream_configurations {
	AMD_CAM_SCALER_AVAILABLE_RECOMMENDED_STREAM_CONFIGURATIONS_PREVIEW =
	    0x0,
	AMD_CAM_SCALER_AVAILABLE_RECOMMENDED_STREAM_CONFIGURATIONS_RECORD = 0x1,
	AMD_CAM_SCALER_AVAILABLE_RECOMMENDED_STREAM_CONFIGURATIONS_VIDEO_SNAPSHOT
	    = 0x2,
	AMD_CAM_SCALER_AVAILABLE_RECOMMENDED_STREAM_CONFIGURATIONS_SNAPSHOT =
	    0x3,
	AMD_CAM_SCALER_AVAILABLE_RECOMMENDED_STREAM_CONFIGURATIONS_ZSL = 0x4,
	AMD_CAM_SCALER_AVAILABLE_RECOMMENDED_STREAM_CONFIGURATIONS_RAW = 0x5,
	AMD_CAM_SCALER_AVAILABLE_RECOMMENDED_STREAM_CONFIGURATIONS_LOW_LATENCY_SNAPSHOT
	    = 0x6,
	AMD_CAM_SCALER_AVAILABLE_RECOMMENDED_STREAM_CONFIGURATIONS_PUBLIC_END =
	    0x7,
	AMD_CAM_SCALER_AVAILABLE_RECOMMENDED_STREAM_CONFIGURATIONS_VENDOR_START
	    = 0x18,
};

// AMD_CAM_SENSOR_REFERENCE_ILLUMINANT1
enum camera_metadata_enum_amd_cam_sensor_reference_illuminant1 {
	AMD_CAM_SENSOR_REFERENCE_ILLUMINANT1_DAYLIGHT = 1,
	AMD_CAM_SENSOR_REFERENCE_ILLUMINANT1_FLUORESCENT = 2,
	AMD_CAM_SENSOR_REFERENCE_ILLUMINANT1_TUNGSTEN = 3,
	AMD_CAM_SENSOR_REFERENCE_ILLUMINANT1_FLASH = 4,
	AMD_CAM_SENSOR_REFERENCE_ILLUMINANT1_FINE_WEATHER = 9,
	AMD_CAM_SENSOR_REFERENCE_ILLUMINANT1_CLOUDY_WEATHER = 10,
	AMD_CAM_SENSOR_REFERENCE_ILLUMINANT1_SHADE = 11,
	AMD_CAM_SENSOR_REFERENCE_ILLUMINANT1_DAYLIGHT_FLUORESCENT = 12,
	AMD_CAM_SENSOR_REFERENCE_ILLUMINANT1_DAY_WHITE_FLUORESCENT = 13,
	AMD_CAM_SENSOR_REFERENCE_ILLUMINANT1_COOL_WHITE_FLUORESCENT = 14,
	AMD_CAM_SENSOR_REFERENCE_ILLUMINANT1_WHITE_FLUORESCENT = 15,
	AMD_CAM_SENSOR_REFERENCE_ILLUMINANT1_STANDARD_A = 17,
	AMD_CAM_SENSOR_REFERENCE_ILLUMINANT1_STANDARD_B = 18,
	AMD_CAM_SENSOR_REFERENCE_ILLUMINANT1_STANDARD_C = 19,
	AMD_CAM_SENSOR_REFERENCE_ILLUMINANT1_D55 = 20,
	AMD_CAM_SENSOR_REFERENCE_ILLUMINANT1_D65 = 21,
	AMD_CAM_SENSOR_REFERENCE_ILLUMINANT1_D75 = 22,
	AMD_CAM_SENSOR_REFERENCE_ILLUMINANT1_D50 = 23,
	AMD_CAM_SENSOR_REFERENCE_ILLUMINANT1_ISO_STUDIO_TUNGSTEN = 24,
};

// AMD_CAM_SENSOR_TEST_PATTERN_MODE
enum camera_metadata_enum_amd_cam_sensor_test_pattern_mode {
	AMD_CAM_SENSOR_TEST_PATTERN_MODE_OFF,
	AMD_CAM_SENSOR_TEST_PATTERN_MODE_SOLID_COLOR,
	AMD_CAM_SENSOR_TEST_PATTERN_MODE_COLOR_BARS,
	AMD_CAM_SENSOR_TEST_PATTERN_MODE_COLOR_BARS_FADE_TO_GRAY,
	AMD_CAM_SENSOR_TEST_PATTERN_MODE_PN9,
	AMD_CAM_SENSOR_TEST_PATTERN_MODE_CUSTOM1 = 256,
};

// AMD_CAM_SENSOR_INFO_COLOR_FILTER_ARRANGEMENT
enum camera_metadata_enum_amd_cam_sensor_info_color_filter_arrangement {
	AMD_CAM_SENSOR_INFO_COLOR_FILTER_ARRANGEMENT_RGGB,
	AMD_CAM_SENSOR_INFO_COLOR_FILTER_ARRANGEMENT_GRBG,
	AMD_CAM_SENSOR_INFO_COLOR_FILTER_ARRANGEMENT_GBRG,
	AMD_CAM_SENSOR_INFO_COLOR_FILTER_ARRANGEMENT_BGGR,
	AMD_CAM_SENSOR_INFO_COLOR_FILTER_ARRANGEMENT_RGB,
	AMD_CAM_SENSOR_INFO_COLOR_FILTER_ARRANGEMENT_MONO,
	AMD_CAM_SENSOR_INFO_COLOR_FILTER_ARRANGEMENT_NIR,
};

// AMD_CAM_SENSOR_INFO_TIMESTAMP_SOURCE
enum camera_metadata_enum_amd_cam_sensor_info_timestamp_source {
	AMD_CAM_SENSOR_INFO_TIMESTAMP_SOURCE_UNKNOWN,
	AMD_CAM_SENSOR_INFO_TIMESTAMP_SOURCE_REALTIME,
};

// AMD_CAM_SENSOR_INFO_LENS_SHADING_APPLIED
enum camera_metadata_enum_amd_cam_sensor_info_lens_shading_applied {
	AMD_CAM_SENSOR_INFO_LENS_SHADING_APPLIED_FALSE,
	AMD_CAM_SENSOR_INFO_LENS_SHADING_APPLIED_TRUE,
};

// AMD_CAM_SHADING_MODE
enum camera_metadata_enum_amd_cam_shading_mode {
	AMD_CAM_SHADING_MODE_OFF,
	AMD_CAM_SHADING_MODE_FAST,
	AMD_CAM_SHADING_MODE_HIGH_QUALITY,
};

// AMD_CAM_STATISTICS_FACE_DETECT_MODE
enum camera_metadata_enum_amd_cam_statistics_face_detect_mode {
	AMD_CAM_STATISTICS_FACE_DETECT_MODE_OFF,
	AMD_CAM_STATISTICS_FACE_DETECT_MODE_SIMPLE,
	AMD_CAM_STATISTICS_FACE_DETECT_MODE_FULL,
};

// AMD_CAM_STATISTICS_HISTOGRAM_MODE
enum camera_metadata_enum_amd_cam_statistics_histogram_mode {
	AMD_CAM_STATISTICS_HISTOGRAM_MODE_OFF,
	AMD_CAM_STATISTICS_HISTOGRAM_MODE_ON,
};

// AMD_CAM_STATISTICS_SHARPNESS_MAP_MODE
enum camera_metadata_enum_amd_cam_statistics_sharpness_map_mode {
	AMD_CAM_STATISTICS_SHARPNESS_MAP_MODE_OFF,
	AMD_CAM_STATISTICS_SHARPNESS_MAP_MODE_ON,
};

// AMD_CAM_STATISTICS_HOT_PIXEL_MAP_MODE
enum camera_metadata_enum_amd_cam_statistics_hot_pixel_map_mode {
	AMD_CAM_STATISTICS_HOT_PIXEL_MAP_MODE_OFF,
	AMD_CAM_STATISTICS_HOT_PIXEL_MAP_MODE_ON,
};

// AMD_CAM_STATISTICS_SCENE_FLICKER
enum camera_metadata_enum_amd_cam_statistics_scene_flicker {
	AMD_CAM_STATISTICS_SCENE_FLICKER_NONE,
	AMD_CAM_STATISTICS_SCENE_FLICKER_50HZ,
	AMD_CAM_STATISTICS_SCENE_FLICKER_60HZ,
};

// AMD_CAM_STATISTICS_LENS_SHADING_MAP_MODE
enum camera_metadata_enum_amd_cam_statistics_lens_shading_map_mode {
	AMD_CAM_STATISTICS_LENS_SHADING_MAP_MODE_OFF,
	AMD_CAM_STATISTICS_LENS_SHADING_MAP_MODE_ON,
};

// AMD_CAM_STATISTICS_OIS_DATA_MODE
enum camera_metadata_enum_amd_cam_statistics_ois_data_mode {
	AMD_CAM_STATISTICS_OIS_DATA_MODE_OFF,
	AMD_CAM_STATISTICS_OIS_DATA_MODE_ON,
};

// AMD_CAM_TONEMAP_MODE
enum camera_metadata_enum_amd_cam_tonemap_mode {
	AMD_CAM_TONEMAP_MODE_CONTRAST_CURVE,
	AMD_CAM_TONEMAP_MODE_FAST,
	AMD_CAM_TONEMAP_MODE_HIGH_QUALITY,
	AMD_CAM_TONEMAP_MODE_GAMMA_VALUE,
	AMD_CAM_TONEMAP_MODE_PRESET_CURVE,
};

// AMD_CAM_TONEMAP_PRESET_CURVE
enum camera_metadata_enum_amd_cam_tonemap_preset_curve {
	AMD_CAM_TONEMAP_PRESET_CURVE_SRGB,
	AMD_CAM_TONEMAP_PRESET_CURVE_REC709,
};

// AMD_CAM_LED_TRANSMIT
enum camera_metadata_enum_amd_cam_led_transmit {
	AMD_CAM_LED_TRANSMIT_OFF,
	AMD_CAM_LED_TRANSMIT_ON,
};

// AMD_CAM_LED_AVAILABLE_LEDS
enum camera_metadata_enum_amd_cam_led_available_leds {
	AMD_CAM_LED_AVAILABLE_LEDS_TRANSMIT,
};

// AMD_CAM_INFO_SUPPORTED_HARDWARE_LEVEL
enum camera_metadata_enum_amd_cam_info_supported_hardware_level {
	AMD_CAM_INFO_SUPPORTED_HARDWARE_LEVEL_LIMITED,
	AMD_CAM_INFO_SUPPORTED_HARDWARE_LEVEL_FULL,
	AMD_CAM_INFO_SUPPORTED_HARDWARE_LEVEL_LEGACY,
	AMD_CAM_INFO_SUPPORTED_HARDWARE_LEVEL_3,
	AMD_CAM_INFO_SUPPORTED_HARDWARE_LEVEL_EXTERNAL,
};

// AMD_CAM_INFO_SUPPORTED_BUFFER_MANAGEMENT_VERSION
enum camera_metadata_enum_amd_cam_info_supported_buffer_management_version {
	AMD_CAM_INFO_SUPPORTED_BUFFER_MANAGEMENT_VERSION_HIDL_DEVICE_3_5,
};

// AMD_CAM_BLACK_LEVEL_LOCK
enum camera_metadata_enum_amd_cam_black_level_lock {
	AMD_CAM_BLACK_LEVEL_LOCK_OFF,
	AMD_CAM_BLACK_LEVEL_LOCK_ON,
};

// AMD_CAM_SYNC_FRAME_NUMBER
enum camera_metadata_enum_amd_cam_sync_frame_number {
	AMD_CAM_SYNC_FRAME_NUMBER_CONVERGING = -1,
	AMD_CAM_SYNC_FRAME_NUMBER_UNKNOWN = -2,
};

// AMD_CAM_SYNC_MAX_LATENCY
enum camera_metadata_enum_amd_cam_sync_max_latency {
	AMD_CAM_SYNC_MAX_LATENCY_PER_FRAME_CONTROL = 0,
	AMD_CAM_SYNC_MAX_LATENCY_UNKNOWN = -1,
};

// AMD_CAM_DEPTH_AVAILABLE_DEPTH_STREAM_CONFIGURATIONS
enum camera_metadata_enum_amd_cam_depth_available_depth_stream_configurations {
	AMD_CAM_DEPTH_AVAILABLE_DEPTH_STREAM_CONFIGURATIONS_OUTPUT,
	AMD_CAM_DEPTH_AVAILABLE_DEPTH_STREAM_CONFIGURATIONS_INPUT,
};

// AMD_CAM_DEPTH_DEPTH_IS_EXCLUSIVE
enum camera_metadata_enum_amd_cam_depth_depth_is_exclusive {
	AMD_CAM_DEPTH_DEPTH_IS_EXCLUSIVE_FALSE,
	AMD_CAM_DEPTH_DEPTH_IS_EXCLUSIVE_TRUE,
};

// AMD_CAM_DEPTH_AVAILABLE_DYNAMIC_DEPTH_STREAM_CONFIGURATIONS
enum camera_metadata_enum_amd_cam_depth_available_dynamic_depth_stream_configurations {
	AMD_CAM_DEPTH_AVAILABLE_DYNAMIC_DEPTH_STREAM_CONFIGURATIONS_OUTPUT,
	AMD_CAM_DEPTH_AVAILABLE_DYNAMIC_DEPTH_STREAM_CONFIGURATIONS_INPUT,
};

// AMD_CAM_LOGICAL_MULTI_CAMERA_SENSOR_SYNC_TYPE
enum camera_metadata_enum_amd_cam_logical_multi_camera_sensor_sync_type {
	AMD_CAM_LOGICAL_MULTI_CAMERA_SENSOR_SYNC_TYPE_APPROXIMATE,
	AMD_CAM_LOGICAL_MULTI_CAMERA_SENSOR_SYNC_TYPE_CALIBRATED,
};

// AMD_CAM_DISTORTION_CORRECTION_MODE
enum camera_metadata_enum_amd_cam_distortion_correction_mode {
	AMD_CAM_DISTORTION_CORRECTION_MODE_OFF,
	AMD_CAM_DISTORTION_CORRECTION_MODE_FAST,
	AMD_CAM_DISTORTION_CORRECTION_MODE_HIGH_QUALITY,
};

// AMD_CAM_HEIC_AVAILABLE_HEIC_STREAM_CONFIGURATIONS
enum camera_metadata_enum_amd_cam_heic_available_heic_stream_configurations {
	AMD_CAM_HEIC_AVAILABLE_HEIC_STREAM_CONFIGURATIONS_OUTPUT,
	AMD_CAM_HEIC_AVAILABLE_HEIC_STREAM_CONFIGURATIONS_INPUT,
};

// AMD_CAM_HEIC_INFO_SUPPORTED
enum camera_metadata_enum_amd_cam_heic_info_supported {
	AMD_CAM_HEIC_INFO_SUPPORTED_FALSE,
	AMD_CAM_HEIC_INFO_SUPPORTED_TRUE,
};

// AMD_CAM_VENDOR_CONTROL_FORCEAPPLY_MODE
enum camera_metadata_enum_amd_cam_vendor_control_forceapply_mode {
	AMD_CAM_VENDOR_CONTROL_FORCEAPPLY_MODE_OFF,
	AMD_CAM_VENDOR_CONTROL_FORCEAPPLY_MODE_ON,
};

// AMD_CAM_VENDOR_CONTROL_EFFECT_MODE
enum camera_metadata_enum_amd_cam_vendor_control_effect_mode {
	AMD_CAM_VENDOR_CONTROL_EFFECT_MODE_OFF,
	AMD_CAM_VENDOR_CONTROL_EFFECT_MODE_GRAYSCALE,
	AMD_CAM_VENDOR_CONTROL_EFFECT_MODE_NEGATIVE,
	AMD_CAM_VENDOR_CONTROL_EFFECT_MODE_SEPIA,
	AMD_CAM_VENDOR_CONTROL_EFFECT_MODE_COLOR_SELECTION,
	AMD_CAM_VENDOR_CONTROL_EFFECT_MODE_SHARPEN,
	AMD_CAM_VENDOR_CONTROL_EFFECT_MODE_EMBOSS,
	AMD_CAM_VENDOR_CONTROL_EFFECT_MODE_SKETCH,
};

// AMD_CAM_VENDOR_CONTROL_LENS_CONTROL_MODE
enum camera_metadata_enum_amd_cam_vendor_control_lens_control_mode {
	AMD_CAM_VENDOR_CONTROL_LENS_CONTROL_MODE_OFF,
	AMD_CAM_VENDOR_CONTROL_LENS_CONTROL_MODE_AUTO,
};

// AMD_CAM_VENDOR_CONTROL_ENGINEERING_MODE
enum camera_metadata_enum_amd_cam_vendor_control_engineering_mode {
	AMD_CAM_VENDOR_CONTROL_ENGINEERING_MODE_OFF,
	AMD_CAM_VENDOR_CONTROL_ENGINEERING_MODE_ON,
};

#endif //__AMD_CAM_METADATA_TAGS_H__
