# SPDX-License-Identifier: MIT

#CFLAGS_sk_alg_amdtee.o := -DDLM_SUPPORT
#CFLAGS_sk_dlm.o := -DDLM_SUPPORT

obj-$(CONFIG_AMDTEE_CCP_AES) += sk_alg_dlm.o
sk_alg_dlm-objs += sk_alg_amdtee.o
sk_alg_dlm-objs += sk_dlm.o

