# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_ARCH_SEATTLE) += amd-overdrive.dtb \
			amd-overdrive-rev-b0.dtb amd-overdrive-rev-b1.dtb \
			husky.dtb
dtb-$(CONFIG_ARCH_MERO_CVIP) += amd-mero-cvip.dtb